language: python
env:
  #- DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
python:
  - "2.6"
  - "2.7"
install:
  - pip install django==$DJANGO_VERSION --use-mirrors
  #- pip install . --use-mirrors
  - pip install -r project_examples/django_example/requirements.txt
#  - pip install pep8 pyflakes --use-mirrors
#before_script:
#  - "cp mezzanine/project_template/local_settings.py.template mezzanine/project_template/local_settings.py"
script:
  - python ./django_example/manage.py test golive
notifications:
  email: "philip.sahli@fatrix.ch"
  on_success: change
  on_failure: always